appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MMKdIwkp8o9DMeaOHHhKm7Q23BCl0TdRYAHifccYKShNAtdSjR2uzwTY1b1FsQuwKTJ8+S4vch0PIwIASwfLct1ZuVWjcjGevDZknkZ5eiNyuMzYhZZacWPLMQA7gvu3jIQ/cHOz/0hibDu17/P5pYacA+hjeP/Ls4EirNnWG8cdHaIXmsJYJOpwVZybayS4TF/xT80IuXMem+wVSq9+xrhlaUe27pLFe0EFu1NQoUFbDscAgRi90/afOmFOGGX0GMD0cNA6R6OFztHKlCtcya6VZxcWCRVo9AsvbIs1+S32ovMYwg0e51rfTxBbA1XJqzHzdzdaOxOrw1nmniMWjGjey1uQf08SMtWZ4Z7VGCnNUHDczuqVwJJwCtkA0WEiiX0JzqM99TLn5qaXxO02cWJ5QHuAextMEHBT3zMiuI9mIfJj6F4KPQhcro90/V9U0UITLCwAMs5Lt0iOSRaHtfJrdfofmdOof7hgD0WlWlOSqXEh5V65MBHeIWAYuKLWgySf/9Nw76N8r2vumJYd586JpzC/gh7c2WLj2zk95rzXyuZ5IrTVohBx0lBZTkGQ2T5RNBofSSR+0HJCVkvCzQG2PyS1QAva9Mdt4pt3/TcpEJt3CFtopDorKzS26+YhwgYP8uMW69uyJ8SwHdL/2EBnCiwUYj59KqJqTmtcJzs=}
conda_forge_output_validation: true
