travis:
  secure:
    BINSTAR_TOKEN: tJ9iGJwZw2HTBq7GWip+wsGEEmbGaH/hHQXx2/5hf4u7RrWtkCTigxtWRtYYCIwFjZEn0GzbgH7dYG2E1XjsUhR9+ae2usCWtDNV1O5Qw3/M9M1KD8+VItxOw8oMTji71Ni41jPcVJpayhWr+4g2+cThWU3RykMeQJT084lhZ6KfG2zfEG7R3bClGVaxr8zeR5VLXfMaPbWLzC+S5mJXuxdKw/dso/CinCLdxEAf3YQnEli/53bHlRazhteLkpDUIpJ8FwvrJVmGsT9G7J1oSu33p7Lf+ifN01o+Ftrj64YaDHe+d6wW91IdjG4P0fLZgeaTqAfjFqSUTZkIpH0bVha0oA9pnlI1G3vRvG6oJxk79F5HCi+V9SL7gGI1e9KJyzTWfWGZqQ3/VFh1E84U7heON9g31IX7RgRUgTHRi03FiF+zEoojUTi18/OSi3g7mSyCkbFBgwNHcyAXkO/TYuBGxhqjNM3YdLPo1w6/j3KJ6+MDb985ZhF/NDgm4DZCO4xoTJVHN8vAMP37G1vWEF4XK0pGfBMy7PhOm0IgR/eoBzAoOHnLy/rtc9IJGY9sCY53WMk4K31VWNvL11E/8T2P2TzGw4cOYye0klpQAO6MW+PERIbgjDPfJZolkfJ1kFidk64pJOP9y6rpdnWuwcKFFsA3rqLE6Hj5k0xBxHw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
